apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-deployment
spec:
  selector:
    matchLabels:
      app: project1-pod
  template:
    metadata:
      labels:
        app: project1-pod
    spec:
      containers:
      - name: project1-container
        image: katuricontainerregistry.azurecr.io/project1:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
